language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  api_key:
    secure: xFOlpNYXm6wUq8zp6NaH3f085hszKUMSapY27WwMJweGXUePdtaWNNCiSOUgmI9AEwGSQqXf456DmllUgqGV630QaM9gg50AMbY9FcFPq0LP1GMhFGmjB1pjD8S1pZFL0nyh07UdCo0Ue4xFJfVdCBADUbJr2lBYYXtxZWWYJTpmGT9ckAfLk/i0aoNX7ijwWPqQQRRisYhUiuaaLS9R3p+W31PhnZ+YfEVEfLjDl5IXm/yhoyqA2cGJ6bm6qRZoRDsut0sdGKjU7kHS0SI/pgHhkYFOsgY2dQQpQjUD49qCmbQWkx0BFo/k5F0Y05nXhkYg3BjkGhqfy9LwjtOPRFGQEcJd8/BtAsOrpSoh/R1/o9QcjlSFAWKGm2qDa1BWNDveqrXKX25m759XNwhYN9Jml4ghwIzH6/db2R2xHLVfAHTZn/Oqo9YzbblWB+v/+C3NHDL5dC7FKpTZkF7LSPjDz7+W40RfTBwyjNxXp/r2pfjGud8gA3vIetPKznxSF9QM822f+w78qK7DUDOdfXeEVyC4Ji6L09Za5Wcejsf6YvCuxFhvszEsVsoUzYd5jxrF72rUTXszTPCet7TxF6R/onMjMBk9tn1OX/gGn1EUJHdba8im+V3vZwP1FsFDmq3h4HCSBrF30usmiF3H3vJUyodrQ5M/D/y+vFrGTxo=
